FROM public.ecr.aws/lambda/python:3.11

# Copy requirements
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt -t /package/

# Output will be in /package/
CMD ["echo", "Dependencies installed in /package/"]
